// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AllVideoAndLive: typeof import('./src/components/liveCard/allVideoAndLive.vue')['default']
    Aside: typeof import('./src/components/aside/aside.vue')['default']
    AsideComp: typeof import('./src/components/aside/asideComp.vue')['default']
    Card: typeof import('./src/components/liveCard/card.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    Header: typeof import('./src/components/header/header.vue')['default']
    HotAside: typeof import('./src/components/hotAside/hotAside.vue')['default']
    Info: typeof import('./src/components/info/info.vue')['default']
    LeaderBoard: typeof import('./src/components/hotAside/leaderBoard.vue')['default']
    Player: typeof import('./src/components/videoPlayer/player.vue')['default']
    Right: typeof import('./src/components/liveCard/right.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Upload: typeof import('./src/components/header/upload.vue')['default']
    VideoCard: typeof import('./src/components/videoCard/videoCard.vue')['default']
    Week: typeof import('./src/components/hotAside/week.vue')['default']
  }
  export interface ComponentCustomProperties {
    vInfiniteScroll: typeof import('element-plus/es')['ElInfiniteScroll']
  }
}
